name: Go

on:
  release:
    types: [published]
    branches:
    - master

jobs:

  build:
    name: Build
    runs-on: windows-latest
    steps:

    - name: Setup Go environment
      uses: actions/setup-go@v2.1.1

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Test
      run: go test -v .
      
    - name: Build
      run: go build -ldflags -H=windowsgui -v -o Wakeup.exe .

    - name: Upload to release
      uses: AButler/upload-release-assets@v2.0
      with:
        files: 'Wakeup.exe'
        repo-token: ${{ secrets.GITHUB_TOKEN }}

