name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: windows-latest
    steps:

    - name: Setup Go environment
      uses: actions/setup-go@v2.1.1

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Test
      run: go test -v .
      
    - name: Codecov
      uses: codecov/codecov-action@v1.0.12
